export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const CHANGE_STATUS = "CHANGE_STATUS";

export const GET_LOGGED_USER = "GET_LOGGED_USER";
export const REMOVE_LOGGED_USER = "REMOVE_LOGGED_USER";

export const SET_GOOGLESPREADSHEET_AUTH = "SET_GOOGLESPREADSHEET_AUTH";
export const UNSET_GOOGLESPREADSHEET_AUTH = "UNSET_GOOGLESPREADSHEET_AUTH";

export const GET_EMPLOYEE_SALARIES = "GET_EMPLOYEE_SALARIES";
export const ADD_EMPLOYEE_SALARIES = "ADD_EMPLOYEE_SALARIES";
export const UPDATE_EMPLOYEE_SALARY_RAISES = "UPDATE_EMPLOYEE_SALARY_RAISES";
export const UPDATE_EMPLOYEE_BONUSES = "UPDATE_EMPLOYEE_BONUSES";
export const UPDATE_EMPLOYEE_PENALTIES = "UPDATE_EMPLOYEE_PENALTIES";
export const UPDATE_EMPLOYEE_LOANS = "UPDATE_EMPLOYEE_LOANS";
export const UPDATE_EMPLOYEE_LOAN_NOTES = "UPDATE_EMPLOYEE_LOAN_NOTES";
export const UPDATE_EMPLOYEE_EXTRA_LOAN_PAYMENTS =
  "UPDATE_EMPLOYEE_EXTRA_LOAN_PAYMENTS";
export const REMOVE_EMPLOYEE_SALARIES = "REMOVE_EMPLOYEE_SALARIES";

export const GET_REPORTS = "GET_REPORTS";
export const GET_REPORTS_DETAILS = "GET_REPORTS_DETAILS";

export const GET_LOANS = "GET_LOANS";

export const SELECTED_DATE = "SELECTED_DATE";
export const GET_SPECIFIC_SALARIES = "GET_SPECIFIC_SALARIESS";
